# Set your colours here.
# You can find the codes here: http://www.ibm.com/developerworks/library/l-tip-prompt/#h1
mainColour=33
infoColour=32

# Setting colour codes for readability
mainColour="\[\e[${mainColour}m\]"
infoColour="\[\e[${infoColour}m\]"

export PS1="\n${mainColour}[\u@${infoColour}\h${mainColour}, \d ${infoColour}\w${mainColour}]\n\t \$ \[\e[0m\]"


unset mainColour
unset infoColour